version: "3.7"
services:
  react:
    container_name: react
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/web
    networks:
      - frontend
    depends_on:
      - express
    stdin_open: true
  express:
    container_name: express
    build: ./server
    ports:
      - "3333:3333"
    volumes:
      - ./server:/server
    networks:
      - backend
    depends_on:
      - database
  database:
    container_name: mysql
    build: ./mysql
    restart: "always"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: defaultdb
    volumes:
      - ./mysql/dockerVolumes:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge
  frontend:
    name: frontend
    driver: bridge
